# Generated by Django 2.2.6 on 2019-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20191023_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesguide',
            name='image',
            field=models.ImageField(default='../static/travello/images/main2.jpg', upload_to='guides'),
        ),
    ]
