# Generated by Django 2.2.6 on 2019-10-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20191026_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdetails',
            name='visiting_on',
            field=models.PositiveIntegerField(),
        ),
    ]
