# Generated by Django 2.2.6 on 2019-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20191026_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_1',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_2',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_3',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_4',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_5',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='packageshotel',
            name='hotel_image_6',
            field=models.ImageField(default=None, upload_to='hotels'),
        ),
    ]
