# Generated by Django 2.2.6 on 2019-10-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20191027_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesvehicle',
            name='vehicle_image_1',
            field=models.ImageField(default=None, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='packagesvehicle',
            name='vehicle_image_2',
            field=models.ImageField(default=None, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='packagesvehicle',
            name='vehicle_image_3',
            field=models.ImageField(default=None, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='packagesvehicle',
            name='vehicle_image_4',
            field=models.ImageField(default=None, upload_to='vehicles'),
        ),
    ]
