# Generated by Django 2.2.6 on 2019-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20191027_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagesvehicle',
            old_name='vehicle_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='packages',
            name='from_location',
            field=models.CharField(default='Bangalore', max_length=100),
        ),
        migrations.AddField(
            model_name='packagesvehicle',
            name='model_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packagesguide',
            name='image',
            field=models.ImageField(upload_to='guides'),
        ),
        migrations.AlterUniqueTogether(
            name='packagesguide',
            unique_together={('guide_id', 'location_id')},
        ),
        migrations.AlterUniqueTogether(
            name='packagesvehicle',
            unique_together={('reg_number', 'location_id')},
        ),
    ]
