# Generated by Django 2.2.6 on 2019-10-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_auto_20191029_0638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagesguide',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='packagesvehicle',
            unique_together=set(),
        ),
    ]
