# Generated by Django 2.2.6 on 2019-10-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_auto_20191029_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_starts_on', models.DateField()),
                ('reporting_time', models.TimeField()),
                ('reporting_location', models.TextField()),
                ('departure_time', models.TimeField()),
                ('departure_location', models.TextField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.Packages')),
            ],
            options={
                'verbose_name_plural': 'General details',
            },
        ),
    ]
