# Generated by Django 2.2.6 on 2019-10-31 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_generaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAndGeneralDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_company_name', models.CharField(max_length=50)),
                ('vehicle_model_number', models.CharField(default=None, max_length=20)),
                ('capacity', models.IntegerField()),
                ('travel_starts_on', models.DateField()),
                ('reporting_time', models.TimeField()),
                ('reporting_location', models.TextField()),
                ('departure_time', models.TimeField()),
                ('departure_location', models.TextField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.Packages')),
            ],
            options={
                'verbose_name_plural': 'Vehicle and general details',
            },
        ),
        migrations.RemoveField(
            model_name='packagesvehicle',
            name='location_id',
        ),
        migrations.DeleteModel(
            name='GeneralDetails',
        ),
        migrations.DeleteModel(
            name='PackagesVehicle',
        ),
    ]
