# Generated by Django 2.2.6 on 2019-10-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_auto_20191031_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleandgeneraldetails',
            name='capacity',
        ),
    ]
