# Generated by Django 2.2.6 on 2019-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_remove_vehicleandgeneraldetails_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleandgeneraldetails',
            name='vehicle_model_number',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
