# Generated by Django 2.2.6 on 2019-10-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0014_auto_20191031_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleandgeneraldetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicleandgeneraldetails',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='travello.Packages'),
        ),
    ]
