# Generated by Django 2.2.6 on 2019-11-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20191031_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_1',
        ),
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_2',
        ),
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_3',
        ),
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_4',
        ),
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_5',
        ),
        migrations.RemoveField(
            model_name='packageshotel',
            name='hotel_image_6',
        ),
        migrations.AlterField(
            model_name='vehicleandgeneraldetails',
            name='vehicle_model_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_image', models.ImageField(upload_to='hotels')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.PackagesHotel')),
            ],
            options={
                'verbose_name_plural': 'Hotel images',
            },
        ),
    ]
