# Generated by Django 2.2.6 on 2019-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_auto_20191101_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleandgeneraldetails',
            name='travel_starts_on',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleandgeneraldetails',
            name='vehicle_model_number',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
